// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WPF_KOZ_LAB1.Migrations
{
    [DbContext(typeof(Laba1Context))]
    partial class Laba1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("WPF_KOZ_LAB1.Models.Bron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DtBron")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("dt_bron");

                    b.Property<int>("InvId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inv_id");

                    b.HasKey("Id");

                    b.HasIndex("InvId");

                    b.ToTable("bron", (string)null);
                });

            modelBuilder.Entity("WPF_KOZ_LAB1.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Fio")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fio");

                    b.Property<int>("Telefon")
                        .HasColumnType("INTEGER")
                        .HasColumnName("telefon");

                    b.HasKey("Id");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("WPF_KOZ_LAB1.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER")
                        .HasColumnName("price");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("WPF_KOZ_LAB1.Models.Skidka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Pers")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pers");

                    b.HasKey("Id");

                    b.ToTable("skidka", (string)null);
                });

            modelBuilder.Entity("WPF_KOZ_LAB1.Models.Type_t", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("type", (string)null);
                });

            modelBuilder.Entity("WPF_KOZ_LAB1.Models.Zakaz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ClentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("clent_id");

                    b.Property<int>("InvId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inv_id");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("ClentId");

                    b.HasIndex("InvId");

                    b.ToTable("zakaz", (string)null);
                });

            modelBuilder.Entity("WPF_KOZ_LAB1.Models.ZakazSkidka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("IdSkidka")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_skidka");

                    b.Property<int>("IdZakaz")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_zakaz");

                    b.HasKey("Id");

                    b.HasIndex("IdSkidka");

                    b.HasIndex("IdZakaz");

                    b.ToTable("zakaz_skidka", (string)null);
                });

            modelBuilder.Entity("WPF_KOZ_LAB1.Models.Bron", b =>
                {
                    b.HasOne("WPF_KOZ_LAB1.Models.Inventory", "Inv")
                        .WithMany("Brons")
                        .HasForeignKey("InvId")
                        .IsRequired();

                    b.Navigation("Inv");
                });

            modelBuilder.Entity("WPF_KOZ_LAB1.Models.Zakaz", b =>
                {
                    b.HasOne("WPF_KOZ_LAB1.Models.Client", "Clent")
                        .WithMany("Zakazs")
                        .HasForeignKey("ClentId")
                        .IsRequired();

                    b.HasOne("WPF_KOZ_LAB1.Models.Inventory", "Inv")
                        .WithMany("Zakazs")
                        .HasForeignKey("InvId")
                        .IsRequired();

                    b.Navigation("Clent");

                    b.Navigation("Inv");
                });

            modelBuilder.Entity("WPF_KOZ_LAB1.Models.ZakazSkidka", b =>
                {
                    b.HasOne("WPF_KOZ_LAB1.Models.Skidka", "IdSkidkaNavigation")
                        .WithMany("ZakazSkidkas")
                        .HasForeignKey("IdSkidka")
                        .IsRequired();

                    b.HasOne("WPF_KOZ_LAB1.Models.Zakaz", "IdZakazNavigation")
                        .WithMany("ZakazSkidkas")
                        .HasForeignKey("IdZakaz")
                        .IsRequired();

                    b.Navigation("IdSkidkaNavigation");

                    b.Navigation("IdZakazNavigation");
                });

            modelBuilder.Entity("WPF_KOZ_LAB1.Models.Client", b =>
                {
                    b.Navigation("Zakazs");
                });

            modelBuilder.Entity("WPF_KOZ_LAB1.Models.Inventory", b =>
                {
                    b.Navigation("Brons");

                    b.Navigation("Zakazs");
                });

            modelBuilder.Entity("WPF_KOZ_LAB1.Models.Skidka", b =>
                {
                    b.Navigation("ZakazSkidkas");
                });

            modelBuilder.Entity("WPF_KOZ_LAB1.Models.Zakaz", b =>
                {
                    b.Navigation("ZakazSkidkas");
                });
#pragma warning restore 612, 618
        }
    }
}
